FROM node:22.11

# Set the working directory
WORKDIR /app

# Copy package.json and pnpm-lock.yaml
COPY package.json pnpm-lock.yaml ./ 

# Install pnpm
RUN npm install -g pnpm 

# Install dependencies in a CI-friendly way
RUN pnpm install --frozen-lockfile --prod --ignore-scripts

# Copy the rest of the application code
COPY . .

# Expose the application's port
EXPOSE 8000

# Start the application
CMD [ "pnpm", "start" ]
